### ISSUE TITLE
Will we use unit test on the project?

### ISSUE THREAD

**Issue by phuanh004** [cse110-sp23-group3/8-ball#1]
Possible unittest:

- [x] `assertTrue` if input `Is this a valid question?`
- [x] `assertFalse` if input `This is not a question`
- [x] `getRandomAnswer` will return a string

**Comment by nsyousef** [comment]
I asked ChatGPT about how to write unit tests without using an external framework. Here is what it said:

![Screenshot 2023-04-22 at 9 53 06 PM](https://user-images.githubusercontent.com/114201888/233820558-ca05513e-ad0f-48ac-b2e6-ab0d45fb8580.png)

**Comment by phuanh004** [comment]
> I asked ChatGPT about how to write unit tests without using an external framework. Here is what it said:
> 
> ![Screenshot 2023-04-22 at 9 53 06 PM](https://user-images.githubusercontent.com/114201888/233820558-ca05513e-ad0f-48ac-b2e6-ab0d45fb8580.png)

That's cool. But make sure you guys have `nodejs` on ur laptop/ pc.

**Comment by nsyousef** [comment]
I think we need to install node.js for Lab 4 anyways.

**Comment by nsyousef** [comment]
More on unit tests: https://stackoverflow.com/questions/58242163/how-to-test-javascript-without-a-framework

**Comment by phuanh004** [comment]
The example above could be done using GitHub action.

```javascript
// Create a file named test.js
// Define a simple add function
function add(a, b) {
  return a + b;
}

// Define a simple test function
function test(name, fn) {
  try {
    fn();
    console.log(`✅ ${name}`);
  } catch (error) {
    console.error(`❌ ${name}`);
    console.error(error);
    process.exitCode = 1;
  }
}

// Write a test case for the add function
test('add(1, 2) should return 3', () => {
  const actual = add(1, 2);
  const expected = 3;
  if (actual !== expected) {
    throw new Error(`Expected ${expected}, but got ${actual}`);
  }
});
```

This code snippet is adapted from https://github.com/remarkablemark/github-actions-nodejs/blob/master/test.js. You can run this test with GitHub actions by creating a file named .github/workflows/test.yml with the following content:

```yaml
name: Test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: node test.js
```
